// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251210141923_dasdaaaaaad")]
    partial class dasdaaaaaad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("Privacy")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Posts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image_path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nr_Comms")
                        .HasColumnType("int");

                    b.Property<int>("Nr_likes")
                        .HasColumnType("int");

                    b.Property<string>("OwnerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 12, 10, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "First seeded post! Beautiful day for a hike in the mountains. 🌲",
                            Image_path = "../assets/img/ben1.jpg",
                            Nr_Comms = 2,
                            Nr_likes = 15,
                            OwnerID = "1"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2025, 12, 10, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "City lights always make for a perfect evening view. ✨",
                            Image_path = "../assets/img/ben1.jpg",
                            Nr_Comms = 10,
                            Nr_likes = 50,
                            OwnerID = "11"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2025, 12, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tried out a new pasta recipe tonight! Highly recommend! 🍝",
                            Image_path = "../assets/img/download.jpg",
                            Nr_Comms = 25,
                            Nr_likes = 120,
                            OwnerID = "12"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2025, 12, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "My little furry friend enjoying the sunshine. ☀️",
                            Image_path = "../assets/img/ben1.jpg",
                            Nr_Comms = 0,
                            Nr_likes = 8,
                            OwnerID = "1"
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2025, 12, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Finally finished building my new development setup! Ready to code. 💻",
                            Image_path = "../assets/img/ben1.jpg",
                            Nr_Comms = 45,
                            Nr_likes = 250,
                            OwnerID = "1"
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Throwback to that incredible sunset on the beach last month. 🌅",
                            Image_path = "../assets/img/download.jpg",
                            Nr_Comms = 5,
                            Nr_likes = 30,
                            OwnerID = "11"
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A thought-provoking visit to the local art gallery today. 🖼️",
                            Image_path = "../assets/img/ben1.jpg",
                            Nr_Comms = 15,
                            Nr_likes = 90,
                            OwnerID = "1"
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Starting the day with a strong cup of coffee. Can't beat it. ☕",
                            Image_path = "../assets/img/download.jpg",
                            Nr_Comms = 1,
                            Nr_likes = 12,
                            OwnerID = "1"
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Miss waking up to this view. Best vacation ever! 🌍",
                            Image_path = "../assets/img/download.jpg",
                            Nr_Comms = 8,
                            Nr_likes = 60,
                            OwnerID = "1"
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2025, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "So excited to announce the launch of my new side project! Link in bio. 🎉",
                            Image_path = "../assets/img/download.jpg",
                            Nr_Comms = 35,
                            Nr_likes = 180,
                            OwnerID = "12"
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Just testing the post upload feature. Ignore this! 🛠️",
                            Image_path = "../assets/img/ben1.jpg",
                            Nr_Comms = 0,
                            Nr_likes = 3,
                            OwnerID = "13"
                        },
                        new
                        {
                            Id = 12,
                            Created = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "My little garden is finally blooming! So much hard work paid off. 🌸",
                            Image_path = "../assets/img/ben1.jpg",
                            Nr_Comms = 7,
                            Nr_likes = 45,
                            OwnerID = "13"
                        },
                        new
                        {
                            Id = 13,
                            Created = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Throwback to an amazing concert last summer. What a vibe! 🎶",
                            Image_path = "../assets/img/download.jpg",
                            Nr_Comms = 11,
                            Nr_likes = 70,
                            OwnerID = "14"
                        },
                        new
                        {
                            Id = 14,
                            Created = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Finished this great book today. Definitely worth the read. 📚",
                            Image_path = "../assets/img/ben1.jpg",
                            Nr_Comms = 2,
                            Nr_likes = 15,
                            OwnerID = "1"
                        },
                        new
                        {
                            Id = 15,
                            Created = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A quiet moment of reflection. 🕊️",
                            Image_path = "../assets/img/ben1.jpg",
                            Nr_Comms = 0,
                            Nr_likes = 5,
                            OwnerID = "14"
                        },
                        new
                        {
                            Id = 16,
                            Created = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "I can't believe this photo went viral! Thanks everyone for the support! 🙏",
                            Image_path = "../assets/img/download.jpg",
                            Nr_Comms = 80,
                            Nr_likes = 500,
                            OwnerID = "1"
                        },
                        new
                        {
                            Id = 17,
                            Created = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This post was probably uploaded by mistake, no engagement. 👻",
                            Image_path = "../assets/img/download.jpg",
                            Nr_Comms = 0,
                            Nr_likes = 0,
                            OwnerID = "1"
                        },
                        new
                        {
                            Id = 18,
                            Created = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hitting a new personal record at the gym today! Hard work pays off. 💪",
                            Image_path = "../assets/img/ben1.jpg",
                            Nr_Comms = 20,
                            Nr_likes = 105,
                            OwnerID = "11"
                        },
                        new
                        {
                            Id = 19,
                            Created = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Discovered the best food truck tacos today! Absolute perfection. 🌮",
                            Image_path = "../assets/img/ben1.jpg",
                            Nr_Comms = 18,
                            Nr_likes = 150,
                            OwnerID = "1"
                        },
                        new
                        {
                            Id = 20,
                            Created = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The first snowfall of the year! Everything looks so peaceful. ❄️",
                            Image_path = "../assets/img/ben1.jpg",
                            Nr_Comms = 4,
                            Nr_likes = 22,
                            OwnerID = "12"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Posts", b =>
                {
                    b.HasOne("Backend.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
